/*
 * Copyright 2014 IBM Corp. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Load the Node modules required
// Express handles the HTTP URI requests
var express = require('express');
var namespace = require('express-namespace');

// Require the Mobile Cloud SDK for Core and Data Node Config
var IBMBluemix = require('IBMBluemix');
var IBMData = require('ibmdata');

// Load the config.json file that is used to hold the App Id
var app = require("./public/bluelist.json");
var config = {
    // change to real application route generated by Bluemix for your application
    applicationRoute : "mbaas.stage1.mybluemix.net",
    // optional: when running on Bluemix, applicationId will be automatically retrieved and overridden
    applicationId : "yourApplicationId"
};

// initialize the SDK with the Application Id
IBMBluemix.initialize(config);

// initialize the Data SDK 
var data = IBMData.initializeService();

// Create an express app and map routing
var app = express();
app.use(express.bodyParser());
app.use(app.router);

//get context root to deploy your application
//the context root is '${appHostName}/v1/apps/${applicationId}'
var mbaasContextRoot = IBMConfig.mbaasContextRoot;

// log all requests
app.all('*', function(req, res, next) {
    console.log("Received request to " + req.url);
    next();
});

// Create resource URIs for the mbaas Context Route
app.namespace(mbaasContextRoot, function() {

    // Define the main GET method for retrieving a full list of items
    app.get('/items', function(req, res) {

        // Retrieve a Query instance of type "Item" and issue a find() action on it 
        // to retrieve all the items (NO PAGING)
        var query = data.Query.ofType("Item");
        query.find().done(function(items) {
            res.send(items);
        },function(err){
            res.status(500);
            res.send(err);
        });
    });

    // Retrieve a single Item using an id
    app.get('/item/:id', function(req, res) {

        // Using the Data SDK create a query and pass in a search parameter
        var query = data.Query.ofType("Item");
        query.find({
            id: req.params.id
        }, {
            limit: 1
        }).done(function(item) {
            if (item.length == 1) {
                res.send(item);
            } else {
                res.status(404);
                res.send("No such item found");
            }
        });
    });

    // Create a new Item using the payload passed 
    app.post('/item', function(req, res) {

        // Create a new Item instance and then save it to the cloud
        var item = data.Object.ofType("Item", req.body);
        item.save().then(function(saved) {
            res.send(saved);
        },function(err) {
            res.status(500);
            res.send(err);
        });

    });

    // Update an existing Item
    app.put('/item/:id', function(req, res) {
        //Get the object with the given id
        data.Object.withId(req.params.id)
        .then(function(item) {
            // Update the Contents of the Object
            item.set(req.body);

            // Save the updated items
            return item.save()
        }).done(function(saved) {
            res.send(saved);
        },function(err){
            console.error("error: ")
            res.send(500, err);
        });        
    });

    // Delete the Item using a unique id
    app.del('/item/:id', function(req, res) {
        //Get the object with the given id so we can delete it
        data.Object.withId(req.params.id)
        .then(function(item) {
            // Delete the Item from the Cloud 
            return item.del();
        }).done(function(deleted) {
            // Validated it was deleted
            var isDeleted = deleted.isDeleted();
            if (deleted.isDeleted()) {
                res.send("Delete Successful.");
            } else {
                res.status(500);
                res.send("delete failed.");
            }
        });
    });
});


// host static files in public folder
console.log(mbaasContextRoot + '/public');

app.use('/public', express.static('public'));

// redirect to cloudcode doc page when accessing the root context
app.get('/', function(req, res) {
    res.redirect('/public/index.html');
});

app.listen(IBMConfig.port);
console.log('Server started at port: ' + IBMConfig.port);
